### ISSUE TITLE
AttributeError: 'Shift' object has no attribute 'node'

### ISSUE THREAD

**Issue by mujakayadan** [akgunberk/Scheduling-Algorithm-with-Python#1]
Full Track:
iteration 33
Traceback (most recent call last):
  File "C:\Users\muham\Desktop\Scheduling-Algorithm-with-Python-master\Shifting_Bottleneck.py", line 303, in <module>
    g.output() # çizelgelenen makineler networke eklendikten sonra iş başlangıç ve bitiş tarihlerini, buna bağlı olarak da critical path i günceller.
  File "C:\Users\muham\Desktop\Scheduling-Algorithm-with-Python-master\Shifting_Bottleneck.py", line 161, in output
    print("makespan: ", self.makespan)
  File "C:\Users\muham\Desktop\Scheduling-Algorithm-with-Python-master\Shifting_Bottleneck.py", line 139, in makespan
    self._update()
  File "C:\Users\muham\Desktop\Scheduling-Algorithm-with-Python-master\Shifting_Bottleneck.py", line 149, in _update
    self._forward()
  File "C:\Users\muham\Desktop\Scheduling-Algorithm-with-Python-master\Shifting_Bottleneck.py", line 121, in _forward
    self.add_node(n, S=S, C=S + self.node[n]['p'])
**AttributeError: 'Shift' object has no attribute 'node'**

Python 3.6 x64

**Comment by rafaellucas3** [comment]
I had a similar error. I am still investigating the problem. I tracked down the origin of part of his code. Here is the link: http://nicky.vanforeest.com/scheduling/cpm/cpmGraph.html#cpmgraph

**Comment by mujakayadan** [comment]
> I had a similar error. I am still investigating the problem. I tracked down the origin of part of his code. Here is the link: http://nicky.vanforeest.com/scheduling/cpm/cpmGraph.html#cpmgraph

Thank you.

**Comment by RickTiel** [comment]
Hello,

I have the same error. And the original code is not available anymore. Did you already found a solution to this problem?

**Comment by Iamfxz** [comment]
self.nodes

**Comment by akgunberk** [comment]
I am sorry I no longer maintain this repo. 
It was my graduation project but its been a while since I code in python. I made this repo public for people like you seeking a solution for its scheduling problem.
Now I am a JS developer and couldn't help you with this issue.
However, if you know the solution open a PR and I would be happy to merge after review.

**Comment by mujakayadan** [comment]
Hello,

Thank you for your answer. It was my gf's homework and I tried it to do. I somehow fixed the code but I do not remember what happened to it, unfortunately. Maybe I deleted it after we broke up 🙂
I am happy to hear about your new job, hayırlı olsun.

Best regards,
Mucahit Kayadan
________________________________
